// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Combination struct {
	Options [][]int32
}

type User struct {
	Username string
	Email    pgtype.Text
	Password pgtype.Text
}
